### PR TITLE
Fixes #1 and #2

### LINKED ISSUE #1: Supply API to create media queries with language support.
I already started [with the implementation](https://github.com/appreciated/grid-layout/tree/master/src/main/java/com/github/appreciated/css/query/values), which I gladly merge to here if you are interested.

[Also the related tests](https://github.com/appreciated/grid-layout/tree/master/src/test/java/com/github/appreciated/css/query/values)

### LINKED ISSUE #2: Allow to apply the media queries directly to an Element
As the title says, it would be awesome if this Addon would allow to bind the media queries directly to an element without client-server-round-trip.

### PR DESCRIPTION
**Pull request by appreciated**
Fixes #1 and Fixes #2

- Introduces a new Class `ClientMediaQuery` that allows applying client side media queries without a client -> server -> client roundtrip, by binding the element it to another element and setting it's css directly as soon as the media query `matches`

- Introduces new Class `MediaQuery` that allows build valid media queries by using a Java api. 
Also the following Media Query Attributes were added:
  -  `AspectRatioAttributes`
  -  `ColorAttributes`
  -  `ColorIndexAttributes`
  -  `DeviceAspectRatioAttributes`
  -  `DeviceHeightAttributes`
  -  `DevicePixelRatio`
  -  `DeviceWidthAttributes`
  -  `HeightAttributes`
  -  `MonochromeAttributes`
  -  `Orientation`
  -  `Scan`
  -  `WidthAttributes`  

- Some basic Tests for the newly added classes

- Corrected the Jetty Plugin to point directly to resource folder to serve the Polymer templates directly

### CODE REVIEW

**Comment by appreciated** [comment]
@jcgueriaud any thoughts to this?

**Comment by jcgueriaud** [comment]
I was in vacation. I'll check it on monday. It seems really nice.

**Comment by appreciated** [comment]
@jcgueriaud So how are things going?

**Comment by jcgueriaud** [comment]
I'm sorry I was busy this week. I merge the request and I will do a new version.

**Pull request merged**
